<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<<<<<<< HEAD
<testsuite ignored="0" hostname="DESKTOP-SK33D9P" failures="0" tests="1" name="Default test" time="14.987" errors="0" timestamp="2025-09-06T12:28:06 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="14.212"/>
=======
<testsuite ignored="0" hostname="DESKTOP-SK33D9P" failures="1" tests="2" name="Default test" time="19.871" errors="0" timestamp="2025-09-07T18:44:55 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="6.182"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="12.665">
    <failure type="java.lang.AssertionError" message="OTP verification failed: Incorrect OTP, 2 attempts left">
      <![CDATA[java.lang.AssertionError: OTP verification failed: Incorrect OTP, 2 attempts left
at pages.LoginPage.validateOtpResult(LoginPage.java:78)
at stepdefinitions.Login.the_user_enters_the_otp(Login.java:39)
at âœ½.the user enters the otp(file:///D:/CapgeminiTesting/Apollo_247_testing_app/src/test/resources/features/login.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
>>>>>>> da471f6 (Day 2: Apollo 247 website launched and logged in)
</testsuite> <!-- Default test -->
